import React, { useEffect, useState } from 'react';
import DigitalHealthCard from '../components/DigitalHealthCard';
const API='http://localhost:8000/api/super-admin';
export default function PatientPortalPage({ user, onLogout }) {
  const [appointments,setAppointments]=useState([]); const [hospitals,setHospitals]=useState([]); const [departments,setDepartments]=useState([]); const [doctors,setDoctors]=useState([]); const [form,setForm]=useState({hospital_id:'',department_id:'',doctor_id:'',appointment_date:'',appointment_time:'09:00',reason:''}); const [message,setMessage]=useState('');
  useEffect(()=>{fetch(`${API}/appointments/`,{credentials:'include'}).then(r=>r.json()).then(d=>setAppointments(d.appointments||[])); fetch(`${API}/hospitals/?status=approved`).then(r=>r.json()).then(d=>setHospitals(d.hospitals||[]));},[]);
  useEffect(()=>{if(!form.hospital_id)return;fetch(`${API}/appointments/options/?hospital_id=${form.hospital_id}`).then(r=>r.json()).then(d=>{setDepartments(d.departments||[]);setDoctors(d.doctors||[]);});},[form.hospital_id]);
  const book=async e=>{e.preventDefault();const r=await fetch(`${API}/appointments/`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(form)});const d=await r.json();setMessage(d.message);if(r.ok){const a=await fetch(`${API}/appointments/`,{credentials:'include'});setAppointments((await a.json()).appointments||[]);}};
  return <div className="py-4 bg-dot-grid min-vh-100"><div className="container"><div className="d-flex justify-content-between align-items-center mb-4"><div><h2 className="fw-bold mb-0">Patient Dashboard</h2><small className="text-muted">Welcome, {user.name}</small></div><button className="btn btn-outline-secondary" onClick={onLogout}>Logout</button></div><div className="row g-4"><div className="col-lg-4"><div className="card border-0 shadow-sm rounded-4 p-4 mb-4"><DigitalHealthCard patient={{...user,patientId:user.patient_id,healthId:user.health_id}}/></div><div className="card border-0 shadow-sm rounded-4 p-4"><h5 className="fw-bold">Book appointment</h5><form onSubmit={book}><select className="form-select mb-2" required value={form.hospital_id} onChange={e=>setForm({...form,hospital_id:e.target.value,department_id:'',doctor_id:''})}><option value="">Choose hospital</option>{hospitals.map(h=><option key={h.hospital_id} value={h.hospital_id}>{h.hospital_name}</option>)}</select><select className="form-select mb-2" required value={form.department_id} onChange={e=>setForm({...form,department_id:e.target.value,doctor_id:''})}><option value="">Choose department</option>{departments.map(d=><option key={d.department_id} value={d.department_id}>{d.name}</option>)}</select><select className="form-select mb-2" required value={form.doctor_id} onChange={e=>setForm({...form,doctor_id:e.target.value})}><option value="">Choose doctor</option>{doctors.filter(d=>!form.department_id||String(d.department_id)===String(form.department_id)).map(d=><option key={d.doctor_id} value={d.doctor_id}>{d.name} — {d.specialization}</option>)}</select><input type="date" className="form-control mb-2" required value={form.appointment_date} onChange={e=>setForm({...form,appointment_date:e.target.value})}/><input type="time" className="form-control mb-2" required value={form.appointment_time} onChange={e=>setForm({...form,appointment_time:e.target.value})}/><input className="form-control mb-2" placeholder="Reason" required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button className="btn btn-primary w-100">Book</button></form>{message&&<div className="small text-muted mt-2">{message}</div>}</div></div><div className="col-lg-8"><div className="card border-0 shadow-sm rounded-4 p-4"><h5 className="fw-bold">My appointments</h5><div className="table-responsive"><table className="table"><thead><tr><th>Date</th><th>Hospital</th><th>Doctor</th><th>Status</th></tr></thead><tbody>{appointments.map(a=><tr key={a.appointment_id}><td>{a.date} {a.time}</td><td>{a.hospital}</td><td>{a.doctor}</td><td>{a.status}</td></tr>)}{!appointments.length&&<tr><td colSpan="4" className="text-center text-muted">No appointments yet.</td></tr>}</tbody></table></div></div></div></div></div></div>;
}
